services:
  - type: web
    name: city-facts-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0